enabled: true
description: Index data into ES with some fields vectorized using BERT
routes:
  - path: /app-store-data/_doc
    method: POST
    classify:
      category: elasticsearch
      acl: index

envs:
  method: POST
  bertURL: ${{ BERT_URL }}

stages:
  - id: authorize user
    use: authorization
  - id: add body for vector requests
    scriptRef: addBody.js
  - id: name_vector
    use: httpRequest
    async: true
    inputs:
      url: "{{bertURL}}/post"
      method: POST
      headers:
        "Content-Type": "application/json"
      body: "{{nameBody}}"
    continueOnError: false
  - id: desc_vector
    use: httpRequest
    async: true
    inputs:
      url: "{{bertURL}}/post"
      method: POST
      headers:
        "Content-Type": "application/json"
      body: "{{descBody}}"
    continueOnError: false
  - id: merge vector
    scriptRef: "mergeVector.js"
    needs:
      - name_vector
      - desc_vector
    continueOnError: false
  - id: index data
    use: elasticsearchQuery
    needs:
      - merge vector