enabled: true
description: Text or aNN based search for the app store
routes:
  - path: /app-store-data/_reactivesearch
    method: POST
    classify:
      category: reactivesearch
      acl: search

envs:
  bertURL: 'http://192.168.0.109:8125'

stages:
  - id: authorize user
    use: authorization
  - id: text search
    scriptRef: "textSearch.js"
  - id: aNN search
    scriptRef: "annSearch.js"
    async: true
  - id: determine search
    scriptRef: "determineSearch.js"
    needs:
      - text search
      - aNN search
  - id: es query
    use: elasticsearchQuery